const path=require('path');
const {JSDOM}=require('jsdom');const fs=require('fs');
const HTML=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const d=new JSDOM(HTML,{runScripts:"dangerously",pretendToBeVisual:true,url:"https://careerpilot.ai/",beforeParse:w=>Object.defineProperty(w,"scrollTo",{value:()=>{},configurable:true})});
const w=d.window;Object.defineProperty(w,"scrollTo",{value:()=>{},configurable:true});w.confirm=()=>true;w.innerWidth=1280;
let P=0,F=0;const fails=[];const ok=(n,c,x)=>{c?P++:(F++,fails.push(n+(x?"  →  "+x:"")))};
const $=i=>d.window.document.getElementById(i);
console.log("\n╔═══ FULL AUTOPILOT — selection and confirmation ═══╗\n");
setTimeout(()=>{
  w.go("autopilot");
  ok("new autopilot action exists",$("fullauto-btn-text")!=null);
  w.selectJobsForFullAuto();
  ok("picker opens",d.window.document.querySelector(".fullauto-modal-overlay")!=null);
  ok("confirmation is visible",d.window.document.querySelector(".fullauto-modal-actions button")!=null);
  const first=d.window.document.querySelector(".fullauto-check");
  if(first)first.checked=true;
  w.confirmFullAutoSelection();
  ok("confirmation closes picker",!d.window.document.querySelector(".fullauto-modal-overlay"));
  ok("selection is rendered",$("fullauto-selected").textContent.includes("1 job"));
  console.log("\n"+"═".repeat(50));console.log(`PASS ${P}    FAIL ${F}`);
  if(F){console.log("\nFAILURES");fails.forEach(f=>console.log("  ✗ "+f))}else console.log("✓ ALL GREEN");
},500);
